"""Add RelationsUIPath

Revision ID: 48cfd5be23bf
Revises: 7bcebd8f265f
Create Date: 2023-08-15 11:12:36.309872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48cfd5be23bf"
down_revision = "7bcebd8f265f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "uipath_jobs", "uipath_folders", ["OrganizationUnitId"], ["Id"]
    )
    op.drop_column("uipath_jobs", "OrganizationUnitFullyQualifiedName")
    op.create_foreign_key(
        None, "uipath_processes", "uipath_folders", ["OrganizationUnitId"], ["Id"]
    )
    op.drop_column("uipath_processes", "OrganizationUnitFullyQualifiedName")
    op.create_foreign_key(
        None,
        "uipath_queuedefinitions",
        "uipath_folders",
        ["OrganizationUnitId"],
        ["Id"],
    )
    op.drop_column("uipath_queuedefinitions", "OrganizationUnitFullyQualifiedName")
    op.create_foreign_key(
        None,
        "uipath_queueitems",
        "uipath_queuedefinitions",
        ["QueueDefinitionId"],
        ["Id"],
    )
    op.create_foreign_key(
        None, "uipath_queueitems", "uipath_folders", ["OrganizationUnitId"], ["Id"]
    )
    op.drop_column("uipath_queueitems", "QueueDefinitionName")
    op.drop_column("uipath_queueitems", "OrganizationUnitFullyQualifiedName")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uipath_queueitems",
        sa.Column(
            "OrganizationUnitFullyQualifiedName",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "uipath_queueitems",
        sa.Column(
            "QueueDefinitionName", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "uipath_queueitems", type_="foreignkey")
    op.drop_constraint(None, "uipath_queueitems", type_="foreignkey")
    op.add_column(
        "uipath_queuedefinitions",
        sa.Column(
            "OrganizationUnitFullyQualifiedName",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "uipath_queuedefinitions", type_="foreignkey")
    op.add_column(
        "uipath_processes",
        sa.Column(
            "OrganizationUnitFullyQualifiedName",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "uipath_processes", type_="foreignkey")
    op.add_column(
        "uipath_jobs",
        sa.Column(
            "OrganizationUnitFullyQualifiedName",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "uipath_jobs", type_="foreignkey")
    # ### end Alembic commands ###
