"""Added synctimes table

Revision ID: 63d9b81c2bc4
Revises: c1374513345c
Create Date: 2024-03-25 15:56:45.543787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d9b81c2bc4'
down_revision = 'c1374513345c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_synctimes',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('TimeStamp', sa.DateTime(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_synctimes_id'), 'schedule_synctimes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_synctimes_id'), table_name='schedule_synctimes')
    op.drop_table('schedule_synctimes')
    # ### end Alembic commands ###
