"""Add Process columns to Process table

Revision ID: 6ae2d3c4854e
Revises: 48cfd5be23bf
Create Date: 2023-08-23 18:59:38.454882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6ae2d3c4854e"
down_revision = "48cfd5be23bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('celery_taskmeta')
    # op.drop_table('celery_tasksetmeta')
    op.add_column(
        "uipath_processes", sa.Column("ProcessKey", sa.String(), nullable=True)
    )
    op.add_column(
        "uipath_processes", sa.Column("ProcessVersion", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uipath_processes", "ProcessVersion")
    op.drop_column("uipath_processes", "ProcessKey")
    # op.create_table('celery_tasksetmeta',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('taskset_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    # sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='celery_tasksetmeta_pkey'),
    # sa.UniqueConstraint('taskset_id', name='celery_tasksetmeta_taskset_id_key')
    # )
    # op.create_table('celery_taskmeta',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('task_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    # sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('name', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    # sa.Column('args', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.Column('kwargs', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.Column('worker', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    # sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('queue', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='celery_taskmeta_pkey'),
    # sa.UniqueConstraint('task_id', name='celery_taskmeta_task_id_key')
    # )
    # ### end Alembic commands ###
