"""Updated Nullables

Revision ID: 6b9660b9c4e1
Revises: 63d9b81c2bc4
Create Date: 2024-07-30 20:54:40.630527

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "6b9660b9c4e1"
down_revision = "63d9b81c2bc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("token", "is_valid", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("token", "authenticates_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "user",
        "created",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user",
        "modified",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("user", "full_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "totp_counter", existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=True)
    op.alter_column("user", "email_validated", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "email_validated", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "totp_counter", existing_type=sa.String(), type_=sa.INTEGER(), existing_nullable=True)
    op.alter_column("user", "full_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user",
        "modified",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user",
        "created",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("token", "authenticates_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("token", "is_valid", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
