"""Added TrackedQueues, added Enable to TrackedProcess

Revision ID: c1374513345c
Revises: 704b34356b18
Create Date: 2023-08-30 18:15:23.240117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c1374513345c"
down_revision = "704b34356b18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracked_queues",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("QueueId", sa.Integer(), nullable=True),
        sa.Column("Strategy", sa.String(), nullable=True),
        sa.Column("CronJob", sa.String(), nullable=True),
        sa.Column("MinRetries", sa.Integer(), nullable=True),
        sa.Column("Enabled", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["QueueId"],
            ["uipath_queuedefinitions.Id"],
        ),
        sa.PrimaryKeyConstraint("Id"),
    )
    op.create_index(
        op.f("ix_tracked_queues_Id"), "tracked_queues", ["Id"], unique=False
    )
    op.add_column(
        "tracked_processes", sa.Column("Enabled", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_processes", "Enabled")
    op.drop_index(op.f("ix_tracked_queues_Id"), table_name="tracked_queues")
    op.drop_table("tracked_queues")
    # ### end Alembic commands ###
